// src/components/features/InstagramSection.jsx
import React, { useState, useEffect } from "react";
import { FadeIn } from "../ui/FadeIn";
import { INSTAGRAM_CONFIG } from "../../data/config";

// High-fidelity fallback data matching @the.sixth.element.210
const FALLBACK_FEED = {
  handle: "the.sixth.element.210",
  profile_url: "https://www.instagram.com/the.sixth.element.210",
  last_synced: "2026-10-05T18:00:00Z",
  posts: [
    {
      id: "post_1",
      is_hero: true,
      type: "reel",
      image_url: "/images/instagram/post_hero_cocktail.jpg",
      permalink: "https://www.instagram.com/the.sixth.element.210",
      caption: "Smoked Tamarind Mezcal & Cardamom Old Fashioned. The alchemy begins when dusk settles over East Sheen.",
      timestamp: "2h ago",
      likes: 184,
      comments: 22,
      tag: "Evening Alchemy",
    },
    {
      id: "post_2",
      is_hero: false,
      type: "photo",
      image_url: "/images/instagram/post_coffee_latte.jpg",
      permalink: "https://www.instagram.com/the.sixth.element.210",
      caption: "Morning ritual. Fresh single-origin flat whites, ethically roasted in South London by @oldspikeroastery.",
      timestamp: "6h ago",
      likes: 142,
      comments: 14,
      tag: "Morning Ritual",
    },
    {
      id: "post_3",
      is_hero: false,
      type: "photo",
      image_url: "/images/instagram/post_spiced_brunch.jpg",
      permalink: "https://www.instagram.com/the.sixth.element.210",
      caption: "Chili crisp poached eggs on whipped herb labneh with toasted sourdough. Weekend brunch serving until 3pm.",
      timestamp: "1d ago",
      likes: 215,
      comments: 31,
      tag: "Brunch Plates",
    },
    {
      id: "post_4",
      is_hero: false,
      type: "photo",
      image_url: "/images/instagram/post_terrace_dog.jpg",
      permalink: "https://www.instagram.com/the.sixth.element.210",
      caption: "The best post-Richmond Park pitstop. Four-legged friends are always welcome on our heated garden terrace.",
      timestamp: "2d ago",
      likes: 328,
      comments: 45,
      tag: "Terrace Life",
    },
    {
      id: "post_5",
      is_hero: false,
      type: "photo",
      image_url: "/images/instagram/post_orange_wine.jpg",
      permalink: "https://www.instagram.com/the.sixth.element.210",
      caption: "Golden Hour (5–7pm Daily). Low-intervention skin-contact orange wines & aperitivo bar bites to close the day.",
      timestamp: "3d ago",
      likes: 167,
      comments: 19,
      tag: "Golden Hour",
    },
  ],
};

export function InstagramSection({ theme }) {
  const [feedData, setFeedData] = useState(FALLBACK_FEED);
  const [hoveredId, setHoveredId] = useState(null);

  useEffect(() => {
    // Attempt to load the cached static JSON feed generated by the sync pipeline
    fetch(INSTAGRAM_CONFIG.feedJsonUrl || "/data/instagram_feed.json")
      .then((res) => {
        if (res.ok) return res.json();
        throw new Error("Local feed JSON not found");
      })
      .then((data) => {
        if (data && data.posts && data.posts.length > 0) {
          setFeedData(data);
        }
      })
      .catch(() => {
        // Silently use fallback feed on any network or parsing error
      });
  }, []);

  const heroPost = feedData.posts.find((p) => p.is_hero) || feedData.posts[0];
  const gridPosts = feedData.posts.filter((p) => p.id !== heroPost?.id).slice(0, 4);

  return (
    <section
      id="instagram-feed"
      style={{
        padding: "90px 24px",
        background: theme.surface,
        position: "relative",
        borderTop: `1px solid ${theme.muted}15`,
        borderBottom: `1px solid ${theme.muted}15`,
      }}
    >
      <style>{`
        @keyframes bentoPulse {
          0% { transform: scale(0.95); opacity: 0.8; }
          50% { transform: scale(1.15); opacity: 1; }
          100% { transform: scale(0.95); opacity: 0.8; }
        }

        .bento-container {
          display: grid;
          grid-template-columns: 1fr;
          gap: 16px;
          max-width: 1140px;
          margin: 0 auto;
        }

        @media (min-width: 860px) {
          .bento-container {
            grid-template-columns: 1.15fr 1fr;
            gap: 20px;
          }
        }

        .bento-subgrid {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 16px;
        }

        @media (min-width: 860px) {
          .bento-subgrid {
            gap: 20px;
          }
        }

        .bento-tile {
          position: relative;
          border-radius: 16px;
          overflow: hidden;
          background: #141210;
          border: 1px solid rgba(191, 138, 47, 0.18);
          transition: transform 0.35s cubic-bezier(0.16, 1, 0.3, 1), box-shadow 0.35s ease, border-color 0.35s ease;
          display: block;
          text-decoration: none;
        }

        .bento-tile:hover {
          transform: translateY(-4px);
          border-color: rgba(191, 138, 47, 0.5);
          box-shadow: 0 16px 36px rgba(0, 0, 0, 0.35);
        }

        .bento-tile img {
          width: 100%;
          height: 100%;
          object-fit: cover;
          display: block;
          transition: transform 0.5s cubic-bezier(0.16, 1, 0.3, 1);
        }

        .bento-tile:hover img {
          transform: scale(1.04);
        }

        .bento-overlay {
          position: absolute;
          inset: 0;
          background: linear-gradient(to top, rgba(15, 13, 10, 0.92) 0%, rgba(15, 13, 10, 0.4) 50%, rgba(15, 13, 10, 0.1) 100%);
          display: flex;
          flex-direction: column;
          justify-content: flex-end;
          padding: 20px;
          color: #F6F4E3;
          transition: opacity 0.3s ease;
        }

        .bento-badge {
          position: absolute;
          top: 14px;
          left: 14px;
          background: rgba(15, 13, 10, 0.75);
          backdrop-filter: blur(8px);
          border: 1px solid rgba(191, 138, 47, 0.3);
          color: #DFAC4E;
          font-size: 11px;
          font-weight: 500;
          letter-spacing: 0.06em;
          text-transform: uppercase;
          padding: 4px 10px;
          border-radius: 999px;
          display: inline-flex;
          align-items: center;
          gap: 5px;
          z-index: 2;
        }

        .bento-insta-icon {
          position: absolute;
          top: 14px;
          right: 14px;
          width: 32px;
          height: 32px;
          border-radius: 50%;
          background: rgba(15, 13, 10, 0.7);
          backdrop-filter: blur(6px);
          border: 1px solid rgba(255, 255, 255, 0.12);
          display: flex;
          align-items: center;
          justify-content: center;
          color: #F6F4E3;
          z-index: 2;
          transition: transform 0.25s ease, background 0.25s ease;
        }

        .bento-tile:hover .bento-insta-icon {
          background: #BF8A2F;
          color: #0F0D0A;
          transform: rotate(12deg) scale(1.1);
        }
      `}</style>

      {/* Header section */}
      <FadeIn>
        <div style={{ textAlign: "center", marginBottom: 44 }}>
          {/* Live Handle Pill */}
          <a
            href={INSTAGRAM_CONFIG.profileUrl}
            target="_blank"
            rel="noopener noreferrer"
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 8,
              padding: "6px 14px",
              borderRadius: 999,
              background: "rgba(191, 138, 47, 0.1)",
              border: `1px solid rgba(191, 138, 47, 0.25)`,
              color: theme.accent || "#BF8A2F",
              fontSize: 12,
              fontWeight: 500,
              letterSpacing: "0.08em",
              textTransform: "uppercase",
              textDecoration: "none",
              marginBottom: 16,
              transition: "all 0.25s ease",
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.borderColor = "#BF8A2F";
              e.currentTarget.style.transform = "translateY(-1px)";
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.borderColor = "rgba(191, 138, 47, 0.25)";
              e.currentTarget.style.transform = "translateY(0)";
            }}
          >
            <span
              style={{
                width: 7,
                height: 7,
                borderRadius: "50%",
                background: "#2ECC71",
                boxShadow: "0 0 8px #2ECC71",
                animation: "bentoPulse 2s infinite ease-in-out",
              }}
            />
            @{INSTAGRAM_CONFIG.handle} · Live Feed
          </a>

          <h2
            style={{
              fontFamily: "'Cormorant Garamond', serif",
              fontSize: "clamp(28px, 4vw, 42px)",
              fontWeight: 400,
              color: theme.heading,
              letterSpacing: "-0.01em",
              marginBottom: 10,
            }}
          >
            Moments at The Sixth Element
          </h2>
          <p
            style={{
              color: theme.muted,
              fontSize: "clamp(13px, 1.8vw, 15px)",
              maxWidth: 580,
              margin: "0 auto",
              lineHeight: 1.6,
            }}
          >
            Specialty coffee, modern Indian plates, dog-friendly terrace moments & natural wines in East Sheen.
          </p>
        </div>
      </FadeIn>

      {/* Asymmetric Bento Grid (Option B) */}
      <div className="bento-container">
        {/* Left Column: Hero Tile */}
        {heroPost && (
          <FadeIn delay={0.1}>
            <a
              href={heroPost.permalink}
              target="_blank"
              rel="noopener noreferrer"
              className="bento-tile"
              style={{
                height: "100%",
                minHeight: 460,
              }}
              onMouseEnter={() => setHoveredId(heroPost.id)}
              onMouseLeave={() => setHoveredId(null)}
              aria-label={`Instagram Reel: ${heroPost.caption}`}
            >
              <div className="bento-badge">
                <span>✦</span> {heroPost.tag || "Featured"}
              </div>

              <div className="bento-insta-icon">
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
                  <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
                  <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
                </svg>
              </div>

              <img src={heroPost.image_url} alt={heroPost.caption} />

              <div className="bento-overlay">
                <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 8, fontSize: 12, color: "#DFAC4E", fontWeight: 500 }}>
                  <span>{heroPost.timestamp}</span>
                  <span>·</span>
                  <span>❤️ {heroPost.likes}</span>
                  <span>💬 {heroPost.comments}</span>
                </div>
                <p
                  style={{
                    fontFamily: "'Outfit', sans-serif",
                    fontSize: 15,
                    lineHeight: 1.5,
                    color: "#FAF8F0",
                    marginBottom: 12,
                    fontWeight: 400,
                  }}
                >
                  {heroPost.caption}
                </p>
                <div
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    gap: 6,
                    fontSize: 12,
                    fontWeight: 600,
                    letterSpacing: "0.05em",
                    textTransform: "uppercase",
                    color: "#DFAC4E",
                  }}
                >
                  View on Instagram <span>↗</span>
                </div>
              </div>
            </a>
          </FadeIn>
        )}

        {/* Right Column: 2x2 Grid of Curated Photos */}
        <div className="bento-subgrid">
          {gridPosts.map((post, idx) => (
            <FadeIn key={post.id} delay={0.15 + idx * 0.08}>
              <a
                href={post.permalink}
                target="_blank"
                rel="noopener noreferrer"
                className="bento-tile"
                style={{ aspectRatio: "1" }}
                onMouseEnter={() => setHoveredId(post.id)}
                onMouseLeave={() => setHoveredId(null)}
                aria-label={`Instagram Post: ${post.caption}`}
              >
                <div className="bento-badge" style={{ fontSize: 10, padding: "3px 8px" }}>
                  {post.tag}
                </div>

                <div className="bento-insta-icon" style={{ width: 28, height: 28 }}>
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
                    <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
                    <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
                  </svg>
                </div>

                <img src={post.image_url} alt={post.caption} loading="lazy" />

                <div
                  className="bento-overlay"
                  style={{
                    padding: 14,
                    opacity: hoveredId === post.id ? 1 : 0.85,
                    background:
                      hoveredId === post.id
                        ? "linear-gradient(to top, rgba(15, 13, 10, 0.95) 0%, rgba(15, 13, 10, 0.6) 60%, rgba(15, 13, 10, 0.2) 100%)"
                        : "linear-gradient(to top, rgba(15, 13, 10, 0.85) 0%, rgba(15, 13, 10, 0.2) 50%, transparent 100%)",
                  }}
                >
                  <p
                    style={{
                      fontFamily: "'Outfit', sans-serif",
                      fontSize: 12,
                      lineHeight: 1.4,
                      color: "#FAF8F0",
                      marginBottom: 6,
                      display: "-webkit-box",
                      WebkitLineClamp: hoveredId === post.id ? 3 : 2,
                      WebkitBoxOrient: "vertical",
                      overflow: "hidden",
                    }}
                  >
                    {post.caption}
                  </p>
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                      fontSize: 11,
                      color: "#DFAC4E",
                    }}
                  >
                    <span>{post.timestamp}</span>
                    <span>❤️ {post.likes}</span>
                  </div>
                </div>
              </a>
            </FadeIn>
          ))}
        </div>
      </div>

      {/* Follow on Instagram CTA */}
      <FadeIn delay={0.4}>
        <div style={{ textAlign: "center", marginTop: 44 }}>
          <a
            href={INSTAGRAM_CONFIG.profileUrl}
            target="_blank"
            rel="noopener noreferrer"
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 10,
              padding: "13px 28px",
              borderRadius: 30,
              background: "transparent",
              border: `1px solid ${theme.accent || "#BF8A2F"}`,
              color: theme.heading,
              fontFamily: "'Outfit', sans-serif",
              fontSize: 13,
              fontWeight: 500,
              letterSpacing: "0.04em",
              textDecoration: "none",
              transition: "all 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background = theme.accent || "#BF8A2F";
              e.currentTarget.style.color = "#0F0D0A";
              e.currentTarget.style.transform = "translateY(-2px)";
              e.currentTarget.style.boxShadow = "0 8px 20px rgba(191, 138, 47, 0.25)";
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = "transparent";
              e.currentTarget.style.color = theme.heading;
              e.currentTarget.style.transform = "translateY(0)";
              e.currentTarget.style.boxShadow = "none";
            }}
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
              <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
              <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
            </svg>
            Follow @{INSTAGRAM_CONFIG.handle} on Instagram
          </a>
          <p style={{ marginTop: 10, fontSize: 11, color: theme.muted, letterSpacing: "0.02em" }}>
            210 Upper Richmond Road West · London SW14 8AH
          </p>
        </div>
      </FadeIn>
    </section>
  );
}
